CREATE TABLE IF NOT EXISTS USR (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    Username VARCHAR(50) NOT NULL,
    Joined_Date TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    Password VARCHAR(64),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS GRP (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    Name VARCHAR(50) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS GRP_MMBR (
    Group_ID INTEGER NOT NULL,
    User_ID INTEGER NOT NULL,
    PRIMARY KEY(Group_ID, User_ID),
    FOREIGN KEY(Group_ID) REFERENCES GRP(ID),
    FOREIGN KEY(User_ID) REFERENCES USR(ID)
);

CREATE TABLE IF NOT EXISTS GRP_MSG (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    Group_ID INTEGER NOT NULL,
    Sender INTEGER NOT NULL,
    Date_Sent TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    Message VARCHAR(1024) NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(Sender) REFERENCES USR(ID),
    FOREIGN KEY(Group_ID) REFERENCES GRP(ID)
);

CREATE TABLE IF NOT EXISTS DRCT_MSG (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    Sender INTEGER NOT NULL,
    Receiver INTEGER NOT NULL,
    Date_Sent TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    Message VARCHAR(1024) NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(Sender) REFERENCES USR(ID),
    FOREIGN KEY(Receiver) REFERENCES USR(ID)
);